name: Build on Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build DLL
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc

      - name: List files in workspace
        run: dir -Recurse
        shell: pwsh

      - name: Compile icon.rc using rc.exe (via Developer Command Prompt)
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          rc /nologo /fo icon.res icon.rc






      - name: Build DLL
        run: cargo build --release

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runeblood_ascension
          path: target/release/runeblood_ascension.dll
