name: Build on Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build DLL
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Locate and Run rc.exe | Compile icon.rc to icon.res
        shell: pwsh
        run: |
          $rcPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -property installationPath
          $rcExe = Join-Path $rcPath 'VC\Tools\MSVC' `
            | Get-ChildItem -Directory `
            | Sort-Object Name -Descending `
            | Select-Object -First 1 `
            | ForEach-Object { Join-Path $_.FullName 'bin\Hostx64\x64\rc.exe' }
          & $rcExe /fo icon.res icon.rc


      - name: Build DLL
        run: cargo build --release

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runeblood_ascension
          path: target/release/runeblood_ascension.dll
