name: Build on Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build DLL
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Compile icon.rc to icon.res
        run: |
          "C:\Program Files (x86)\Windows Kits\10\bin\**\x64\rc.exe" /fo icon.res icon.rc

      - name: Build DLL
        run: cargo build --release

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runeblood_ascension
          path: target/release/runeblood_ascension.dll
