name: Manual Release Build

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Release DLL
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc

      - name: List files in workspace
        run: dir -Recurse
        shell: pwsh

      - name: Compile icon.rc using rc.exe
        shell: pwsh
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -property installationPath
          
          $msvcToolPath = Join-Path $vsPath 'VC\Tools\MSVC'
          $latestMsvc = Get-ChildItem $msvcToolPath | Sort-Object Name -Descending | Select-Object -First 1
          $rcExePath = Join-Path $latestMsvc.FullName 'bin\Hostx64\x64\rc.exe'

          $command = "`"$rcExePath`" /nologo /fo icon.res icon.rc"
          Write-Host "Using rc.exe: $rcExePath"
          Write-Host "Running: cmd /c $command"

          cmd /c $command





      - name: Build DLL
        run: cargo build --release

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Stable-1.0.0"
          name: "Stable 1.0.0"
          files: target/release/runeblood_ascension.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
