name: Manual Release Build

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Release DLL
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build DLL
        run: cargo build --release

      
      - name: Gerar arquivo de licenças de dependências
        run: |
          cargo install cargo-about
          cargo about generate about.hbs > license.html


      - name: Preparar arquivos para release
        run: |
          mkdir release_files
          copy target\release\runeblood_ascension.dll release_files\
          copy license.html release_files\

      
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Stable-1.0.1"
          name: "Stable 1.0.1"
          files: |
            release_files/runeblood_ascension.dll
            release_files/LICENSE
            release_files/THIRD_PARTY_LICENSES.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
